export const STAGE = 'production';
export const REGION = 'us-east-1';
export const NODE_ENV = STAGE;
export const NODE_OPTIONS = '--enable-source-maps --stack-trace-limit=1000';
export const AWS_NODEJS_CONNECTION_REUSE_ENABLED = '';
export const DYNAMO_ORDERS_TABLE = ``;
export const COGNITO_USER_POOL_ID = ``;
export const COGNITO_CLIENT_ID = ``;
export const SNS_ORDER_PROCESS_TOPIC = ``;
export const SNS_ORDER_POSTPROCESS_TOPIC = ``;
